### ISSUE TITLE
Can't permanently change session locale

### ISSUE THREAD

**Issue by mateuswetah** [telegraf/telegraf-i18n#10]
Hi there, thanks for the middleware, at first.

This is probably more a lack of understanding from me. I'm trying to set commands to change the language, just as you demonstrated in the example file. The problem is that whenever I call  `i18n.locale('pt')`, it does change the language, but only for that message reply. If then I call another message and reply, this comes in the default language ('en').

I suppose this has something to do with me not using the session feature, but I did that because I'm using mysql session middleware instead of the memory one. Also, I see that we're calling i18n from the context of a message so... yeah,  makes sense that it works only there. But how would I change it globally?

Could you help me finding out how it would work? This is my first attempt on Telegraf.

**Comment by dotcypress** [comment]
Hey @mateuswetah 

Actually you can use `any` session middleware (memory, redis, etc.) with `telegraf-i18n`

If you want to set default language explicitly, just use `defaultLanguage` config param:
```js
const i18n = new TelegrafI18n({
  defaultLanguage: 'pt'
})
```

**Comment by mateuswetah** [comment]
Hey thanks for the answer and sorry for the delay!
So, I was able to do it using `i18n.defaultLanguage = 'pt';`. 
Hope that is correct. If so, we can close this :)
