### ISSUE TITLE
Сontext i18n is inaccessible in 'Telegraf/Stage' scene action

### ISSUE THREAD

**Issue by reg2005** [telegraf/telegraf-i18n#11]
Hi! Please help me. I am used Telegraf/Stage (Simple scene-based control flow middleware). But when i'am in scene/Action have an error: 

> Cannot read property 't' of undefined

ctx.i18n also undefined. It should be noted that in 'scene/Enter' ctx.i18n.t is working.

If i make 'scene.use(i18n.middleware())' in scene file the problem will be solved.

How to fix this bug?
Thanks!

**Comment by dotcypress** [comment]
Hey @reg2005 

You should register i18n middleware before stage one:

```js
bot.use(stage.middleware())
bot.use(i18n.middleware())
```

**Comment by reg2005** [comment]
@dotcypress Wow! Thanks!

**Comment by SergoZheludkov** [comment]
yeaaaaaah!) Thanks!)
