### ISSUE TITLE
custom template functions

### ISSUE THREAD

**Issue by akeinhell** [telegraf/telegraf-i18n#15]
Is it possible to add your own functions to the templates, for example pluralize.js?

example 
```
const i18n = new telegrafI18n({
    context: {
        functions: {
            hello: (str) => `great ${str}`
        }
    }
});
```

template:
```yaml
key:
   hello, ${hello('world')}
```

will be produce string `hello, great world`

**Comment by dotcypress** [comment]
@akeinhell from version `6.6.0` you can define custom functions for template engine. [See example](https://github.com/telegraf/telegraf-i18n/blob/develop/examples/example-bot.js#L13)
