### ISSUE TITLE
[BUG] directory: path.resolve(__dirname, "locales")

### ISSUE THREAD

**Issue by weijinnx** [telegraf/telegraf-i18n#19]
```js
// i18n options
const i18n = new TelegrafI18n({
  defaultLanguage: "ru",
  useSession: true,
  directory: path.resolve(__dirname, "locales")
});
```

when try to start bot it says:
`Cannot convert undefined or null to object` - it is related with the directory attribute of i18n config object. Who knows what is it and how can I resolve  this issue?

**Comment by dmbaranov** [comment]
Hey @weijinnx I had similar issue with Typescript. I solved it by adding`"resolveJsonModule": true,` to my tsconfig.json Not sure if it helps, but still. Make sure that you actually can access locales folder and files in it.

**Comment by weijinnx** [comment]
@dmbaranov thanks! It helps. Do you know can I load locales, not from 1 folder? I want to load locales from a few directories.

**Comment by dmbaranov** [comment]
Well, not sure. According to the source code, it accepts the string as a path to the directory and loads all the files from there. What you can try is, create a locales (or whatever) directory and put symlinks there which are pointing to the different folders.

**Comment by dmbaranov** [comment]
Even though I don't have such a case, it would be interesting to see your solution :)
