### ISSUE TITLE
Suggestion: Add a method to get other translations from the same resource

### ISSUE THREAD

**Issue by andrrms** [telegraf/telegraf-i18n#41]
This module should add a method to access a resource from another language from the actual setten, like:
```javascript
ctx.i18n.tFromLang('hello.world', 'en-US'); // "Hello world"
ctx.i18n.tFromLang('hello.world', 'pt-BR'); // "Olá mundo"
ctx.i18n.tFromLang('hello.world', 'de-CH'); // "Hallo Welt"
```

**Comment by EdJoPaTo** [comment]
You can use `const template = ctx.i18n.getTemplate('de-CH')` and call the template with a data object `template({})`.
Otherwise you can just use the main class (not from ctx):
```js
const i18n = new 18n()
const result = i18n.t('de-CH', 'hello.world')
```
