### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 't') in WizardScene

### ISSUE THREAD

**Issue by mootfrost** [telegraf/telegraf-i18n#46]
Everything works, but in the second stage of the scene, i18n is undefined. i18n is registered, as are the scenes in the bot.
```javaScript
const createPostHere = new Scenes.WizardScene('createPostHere',
    async (ctx) => {
        ctx.wizard.state.post = {}
        await ctx.reply(await ctx.i18n.t('createPost.promptTitle')) << everything works
        ctx.wizard.next()
    },
    async (ctx) => {
        ctx.wizard.state.post.title = ctx.message.text
        await ctx.reply(await ctx.i18n.t('createPost.promptText')) << node crashes
        ctx.wizard.next()
    },
```
```javaScript
bot.use(stage.middleware());
bot.use(i18n.middleware())
```
I really don`t know where is the problem

**Comment by EdJoPaTo** [comment]
I have no clue what the Wizard does internally as I never used it. ~~Just as an idea without much thought about it: have you tried `bot.use(i18n)` before the stage middleware?~~

**Comment by EdJoPaTo** [comment]
Ah wait… type Error… I think you need to specify the I18nContext type to the WizardScene so it knows you are not using the default context of telegraf.

Probably something like this:

```ts
export interface MyContext extends TelegrafContext {
  i18n: I18nContext;
}

WizardScene<MyContext>(…)
```

I havnt used Wizard and havnt used telegraf since grammY came out so I might miss some changes to telegraf since then.

**Comment by Adkhambek** [comment]
The main proplem is in middleware. You shoud use i18n first and stage next. like this: 

bot.use(stage.middleware());
bot.use(i18n.middleware())

**Comment by mootfrost** [comment]
@Adkhambek. Now I don't remember how the problem was solved, but it definitely didn't depend on the order of adding to middleware

**Comment by wolterlife** [comment]
@Mootfrost777.
You don't remember how? Adding context didn't help :(

**Comment by mootfrost** [comment]
> @Mootfrost777. You don't remember how? Adding context didn't help :(

There is a workaround by simply saving i18n:
```js
if (ctx.i18n != null) {
    ctx.scene.state.i18n = ctx.i18n
}
```
But I think it breaks every documented and verbal rules. It would be good to know if you find correct solution.
