### ISSUE TITLE
pluralize function should use actual locale

### ISSUE THREAD

**Issue by ofstudio** [telegraf/telegraf-i18n#5]
`pluralize` function should use _actual_ locale instead of user session locale.

Workaround:
```
const i18n = new TelegrafI18n({
  sessionName: 'session',
  defaultLanguage: 'ru',
  allowMissing: true,
  directory: path.resolve(__dirname, 'locales')
});

app.use(Telegraf.memorySession());
app.use(i18n.middleware());
app.use((ctx, next) => {
  ctx.i18n.locale('ru'); // <- Force using Russian pluralization rules
  next()
});
```

**Comment by dotcypress** [comment]
What do you mean `actual locale`?

**Comment by ofstudio** [comment]
At the moment, the session locale value used as a parameter for pluralization function. Regardless of which yaml is actually used.

For example: if my bot contains only Russian locale (`defaultLanguage: 'ru'`) and some user have 'en' session locale – in this case the rules of English pluralization will be applied to the `ru.yaml` strings.

**Comment by dotcypress** [comment]
In v `6.0.0` session support is switched off by default.
