### ISSUE TITLE
Needs to sanitize html entities in telegram.sendCopy

### ISSUE THREAD

**Issue by ofstudio** [telegraf/telegraf-i18n#6]
**The code**
```
app.on('message', ctx => {
  ctx.telegram.sendCopy(ctx.from.id, ctx.message);
});
```

### Case 1
**Input**   
`Let's **test** __markdown__`

**Result** (fine as expected)   
![screen shot 2017-08-21 at 19 49 12](https://user-images.githubusercontent.com/2184504/29529929-4bf4c684-86aa-11e7-9523-98a56f245cf2.png)

### Case 2
**Input**   
`Let's **test** __markdown__ and <b>some</b> HTML`

**Result** (`some` became **bold**, which should not be )    
![screen shot 2017-08-21 at 19 49 40](https://user-images.githubusercontent.com/2184504/29529979-820dd97c-86aa-11e7-8d00-73f783351747.png)

### Case 3
**Input**   
`<b>Some html<b>  and some __markdown__ text`

**Result** (no response due to error)   
![screen shot 2017-08-21 at 19 50 15](https://user-images.githubusercontent.com/2184504/29530069-dbc32512-86aa-11e7-8e2c-df005f63103f.png)

```
(node:42651) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1): 
Error: 400: Bad Request: can't parse entities in message text: 
Expected end tag at byte offset 12
```

Tested on 
- [Telegram Desktop 1.1.18](https://desktop.telegram.org/changelog)
- [Telegram for Android 4.2.2](https://play.google.com/store/apps/details?id=org.telegram.messenger)
- _Telegram for iOS currently does not support markdown entities_

**Comment by dotcypress** [comment]
Hey.

It will be fixed in main Telegraf repo.
Closing for now.
